### ISSUE TITLE
Paths should be relative to the web root

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/content-x#5]
@servilla Referencing files from the web root actually works in GitHub preview (e.g.: https://github.com/PASTAplus/content-x/blob/test_links/templates/resources/citing-data.md) so I think our "relative link mapping issue" is solved. Let me know if you're in agreement and I'll update the links in content-x markdown files.

**Comment by servilla** [comment]
Hi @clnsmth. The webroot does not begin at path fragment "/templates", but rather one of either "/", "/about", "/resources", or "/support". Beginning your document links with "/templates" however is a better approach since it is easily replaced in the build.py script (it's consistent, whereas "../something" is too ambiguous).

**Comment by clnsmth** [comment]
Thanks @servilla. I'll update the page links to this new approach and update build.py to transform them to web root.

**Comment by servilla** [comment]
Best to hold off on modifying build.py - I've made considerable changes, including the removal of `/templates` out of the MD URL strings.

**Comment by clnsmth** [comment]
All page links now begin with `/templates`.

**Comment by servilla** [comment]
Seems to be resolved at this point.
